### ISSUE TITLE
STA9750 aaronkcooper MiniProject #01

### ISSUE THREAD

**Issue by aaronkcooper** [aaronkcooper/STA9750-2024-FALL#2]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #01 - check it out!

https://aaronkcooper.github.io/STA9750-2024-FALL/mp01.html

**Comment by michaelweylandt** [comment]
Thanks @aaronkcooper !

Peer Feedback:

- @fatima8808
- @haolinnn
- @Gautam-1-R
- @Slyastrologer

It is now time for the peer feedback round for Mini-Project #01. Please
review @aaronkcooper's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric,
please grade their submission out of a total of 50 points.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @aaronkcooper, but you are of course
welcome to initiate a discussion.

@aaronkcooper: please engage fully with your peers. They are here to help you!

Submission URL should be: https://aaronkcooper.github.io/STA9750-2024-FALL/mp01.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by fatima8808** [comment]
Hi @aaronkcooper, you did a great job completing our first mini project! I really like how you went above and beyond in including visualizations in your report and explaining your findings. 

Written Communication: 8.5/10 
I think you did a great job when cominig up with your own questions and analyzing the results. For the most part, your report flowed nicely and you explained each step. It may seem a bit difficult trying to incorporate all of the tasks' answers while putting it together like a written analysis, but I think a little more context or explanation would be helpful. 

Project Skeleton: 10/10

Formatting & Display: 8/10
Nice job including the tables, one suggestion I would give is to include some tables for the earlier questions asked in the report. I also think it would be a great idea to select only certain columns to be shown in your table so that readers can see it in one view (instead of scrolling right for the results). 

Also, because you created a few graphical visualizations, I would give some extra credit in this category: +1

Code Quality: 10/10

Data Preparation: 10/10

Total: 47.5/50

**Comment by haolinnn** [comment]
Hi @aaronkcooper, you did a very great job on this project!

Written communication: 9/10
I think you did a great job on this part. You explained every step clearly and the whole report flowed well. It would be better if you could put some analysis for task 3, not just answering the questions.

Project Skeleton: 10/10

Formatting & Display: 10/10
Good job on showing tables and all the graphs!

Code Quality: 10/10

Data Preparation: 10/10

Total: 49/50

**Comment by charles-ramirez** [comment]
Hi, @Gautam-1-R @slyastrologer,

This is just a reminder that your peer review is due today at 11:45 pm.

**Comment by Gautam-1-R** [comment]
Hi @aaronkcooper 
	1.	Written Communication: 7/10
		Good analysis, but could use more context in some areas.
	2.	Project Skeleton: 8.5/10
		Well-structured, just needs minor adjustments.
	3.	Formatting & Display: 8/10
		Nice tables and visualizations. Fewer columns would improve readability.
	4.	Code Quality: 8.5/10
		Clean code, with some room for optimization.
	5.	Data Preparation: 8/10
		Data preparation was good, but could be slightly improved.

Total Rating: 40/50

Good job overall! Keep improving.
